nodeLinker: node-modules

yarnPath: .yarn/releases/yarn-3.6.4.cjs

npmScopes:
  fortawesome:
    npmRegistryServer: "https://npm.fontawesome.com/"
    npmAuthToken: "89E641FD-C2B1-4E83-A258-0FE2F0BD5698"
