const ProductCategory = {
	LOW_SEASON_TRAVELLER: "LOW_SEASON_TRAVELLER",
	CAR_RENTAL: "CAR_RENTAL",
	E_SIM: "E_SIM",
	MEET_AND_GREET: "MEET_AND_GREET",
	LOUNGE: "LOUNGE",
	PORTER: "PORTER",
	MOBILITY_ASSIST: "MOBILITY_ASSIST",
};

export default ProductCategory;
